name: example
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # An exact version pin will be provided by the Flutter SDK.
  intl: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1

  charcode: ^1.1.3
  flutter_keyboard_visibility: ^6.0.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  linkify: ^5.0.0
  logging: ^1.3.0
  uuid: ^4.5.1

  super_editor:
    git:
      url: https://github.com/superlistapp/super_editor.git
      path: super_editor
  super_editor_markdown:
    git:
      url: https://github.com/superlistapp/super_editor.git
      path: super_editor_markdown
  super_text_layout:
    git:
      url: https://github.com/superlistapp/super_editor.git
      path: super_text_layout
  super_keyboard: ^0.2.0
  follow_the_leader: 0.0.4+8
  overlord: 0.0.3+5

dependency_overrides:
  # Override to local mono-repo path so devs can test this repo
  # against changes that they're making to other mono-repo packages
  super_editor:
    path: ../
  super_editor_markdown:
    path: ../../super_editor_markdown
  super_text_layout:
    path: ../../super_text_layout
  attributed_text:
    path: ../../attributed_text

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
#  integration_test:
#    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true # for localization

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: UbuntuMono
      fonts:
        - asset: assets/fonts/Ubuntu_Mono/UbuntuMono-Regular.ttf
        - asset: assets/fonts/Ubuntu_Mono/UbuntuMono-Italic.ttf
          style: italic
        - asset: assets/fonts/Ubuntu_Mono/UbuntuMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/Ubuntu_Mono/UbuntuMono-BoldItalic.ttf
          style: italic
          weight: 700
