publish_to: "none"

name: super_editor
description: Configurable, composable, extensible text editor and document renderer for Flutter.
version: 0.3.0-dev.11
homepage: https://github.com/superlistapp/super_editor
funding:
  - https://flutterbountyhunters.com
  - https://github.com/sponsors/matthew-carroll
topics:
  - rich-text-editor
  - editor
  - quill
  - markdown

screenshots:
  - description: "SuperEditor on Mac desktop"
    path: doc/marketing/screenshot_mac_desktop.png
  - description: "SuperEditor dark mode"
    path: doc/marketing/screenshot_mac_desktop_dark-mode.png
  - description: "SuperEditor text selection"
    path: doc/marketing/screenshot_mac_desktop_text-selection.png
  - description: "SuperEditor text styles"
    path: doc/marketing/screenshot_mac_desktop_bold-selection.png

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

  attributed_text:
    path: packages/attributed_text
  follow_the_leader:
    path: packages/follow_the_leader
  linkify:
    path: packages/linkify
  overlord:
    path: packages/overlord
  super_text_layout:
    path: packages/super_text_layout
  super_keyboard:
    path: packages/super_keyboard
  super_editor_markdown:
    path: packages/super_editor_markdown
  characters: ^1.3.0
  collection: ^1.15.0
  http: ^1.2.2
  logging: ^1.3.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1

 

  clock: ^1.1.1

dev_dependencies:
 # Dependencies for testing tools that we ship with super_editor
  flutter_test:
    sdk: flutter
  flutter_test_robots:
    path: packages/flutter_test_robots
  flutter_lints: ^2.0.1
  golden_toolkit: ^0.15.0
  mockito: ^5.0.4
  text_table: ^4.0.1
  meta: ^1.8.0
  args: ^2.3.1
  path: ^1.8.3
  golden_runner:
    path: packages/golden_runner
  flutter_test_runners: ^0.0.4
  golden_bricks: ^1.0.0
  melos: ^6.3.3

