publish_to: "none"

name: super_editor_quill
description: "Quill extensions for Super Editor"
version: 0.1.0-dev.2
homepage: https://github.com/superlistapp/super_editor

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  super_editor:
    path: ../../
  attributed_text:
    path: ../attributed_text
  logging: ^1.3.0
  dart_quill_delta: ^9.4.1
  collection: ^1.18.0

  # For public testing tools
  matcher: ^0.12.16+1
  text_table: ^4.0.3


dev_dependencies:
  # Note: some testing dependencies are listed as regular dependencies
  #       so we can export testing tools.
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
