include: package:flutter_lints/flutter.yaml

analyzer:
    exclude: [build/**]

linter:
    rules:
        omit_local_variable_types: false
        use_key_in_widget_constructors: false
        avoid_renaming_method_parameters: false
