
publish_to: "none"

name: super_editor_markdown
description: Markdown (de)serialization for super_editor documents.
version: 0.1.5
homepage: https://github.com/superlistapp/super_editor

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  logging: ^1.3.0
  markdown: ^7.2.1
  super_editor:
    path: ../../
  attributed_text:
    path: ../attributed_text


dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_test_robots: 
    path: ../flutter_test_robots
  flutter_test_runners: ^0.0.4
  golden_toolkit: ^0.15.0


